### ISSUE TITLE
Add direct support for std::unique_ptr and std::shared_ptr

### ISSUE THREAD

**Issue by craiggraham** [Smurf-IV/FluentAssertions-for-Cpp#4]
Where using smart pointers, at present checks have to be of the form

Assert().ThatPtr(lineTest.get()).Should().NotBeNull("Returned line should not be null");

It'd be more intuitive to be able to use

Assert().ThatPtr(lineTest).Should().NotBeNull("Returned line should not be null");

Or even 

Assert().That(lineTest).Should().NotBeNull("Returned line should not be null");

**Comment by Smurf-IV** [comment]
![image](https://github.com/user-attachments/assets/1f23d323-229b-4fc6-99fe-47b1d26f9f7a)
